### ISSUE TITLE
still being maintained?

### ISSUE THREAD

**Issue by Korede-TA** [benjamminf/luminate#2]
**context:**  this looks like a cool tool! having a standalone component system for managing state and encapsulating features would be really helpful on a static jekyll site i'm building. i have small wrappers for binding state btwn dom nodes, query params and JS variables, but encapsulation is still tricky.

**Q:** is this still being maintained? is this open to external maintainers? are you aware of any other similar project?

**Comment by benjamminf** [comment]
Hey, just found this after a bored night exploring my old GitHub repo's, so please forgive me for not replying months ago!

Short answers are no, it's not maintained, and I'm sadly unaware of anything similar. I think it's for good reason as the use case this was originally designed for is outmoded and fading in favour of just using React or Vue.

In the five or six years since I initially wrote this I've learned a thing or two, and one of those is that it's usually not a good idea to rely on your DOM to maintain state. I'd recommend against using this library or anything like it.

However if you'd still like to explore this approach, you can pretty much do everything here with [native custom components](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements). It's a somewhat similar developer experience.
